### PR TITLE
fix: add support for branchName and parentBranchName

### PR DESCRIPTION
**Pull request by Trawais**

### CODE REVIEW

**Comment by itaibh** [comment]
Thanks @Trawais !

**Comment by Trawais** [comment]
Hi. Thanks for super fast merge. Will you create new bugfix release or should I use master branch instead?

**Comment by itaibh** [comment]
Use the Master branch for now. There are not enough changes to justify a new release and I don't have much time to do it anyway.
The PHP SDK still needs a  lot of work to get it to fully support everything the other SDKs support, and we'll get there, just not now.

Sorry for the inconvenience.

Itai.

**Comment by Trawais** [comment]
It's completely fine. We will use master and we are happy :) Thanks a lot again.

**Pull request merged**
