### PR TITLE
Fixed missing type bug by creating new CheckSettings instead of using…

### PR DESCRIPTION
**Pull request by svwu**
… null as default

### CODE REVIEW

**Comment by svwu** [comment]
This PR fixes the issue when using checkWindow or checkImage function.
Otherwise we can't use eyes.sdk!

**Review by Trawais — COMMENTED** [review]
Seems OK to me.

**Review by Trawais — APPROVED** [review]

**Comment by svwu** [comment]
I would love to have some progress of applitools here...

**Comment by Trawais** [comment]
Exactly. I would love to be a contributor and ensure some progress by myself :)

**Comment by itaibh** [comment]
Hi @svwu, I'm Itai from Applitools.

We're currently focusing on other platform as PHP doesn't have enough request and we don't have the HR to put someone on this full time (or any time).

I suggest you open a support ticket with our Customer Success team at [https://applitools.com/contact](https://applitools.com/contact) and explain the issue you're having. I believe they'll be able to help you or escalate this to the R&D team, so it gets prioritized.

Sorry, and thank you for your interest in Applitools.

**Comment by svwu** [comment]
Hello @itaibh ,
that's why Opensource is great! :)
We're happy to contribute and help in this regard!
You can simply find contributors and give access to this repository that developers can improve and fix this project.

I already opened few tickets but I didnt got any response, I am deeply disappointed right now, cause I have tried so many times to get this bug fixed which is actually a just one line of code?

**Comment by Trawais** [comment]
Exactly. I'm with Sven.

**Comment by danielputerman** [comment]
@svwu @Trawais Thanks for the PR and sorry for the late response. We'll do a quick verification today and merge if all's good

**Comment by danielputerman** [comment]
@Trawais @svwu First, first thanks for your feedback,and pologies for the major delay in response. Second, As I mentioned, we reviewed the bug and the PR. Simply creating a CheckSettings instance in the matchWindow method would have caused issues in another flow, so we had to do another fix,
which you can see in this commit: fb969fcd0d7cacbd048f3fe709a58441712d23e6
We've  published version 1.3.2, which includes this fix.

Thanks!

**Comment by danielputerman** [comment]
Fixed in [version 1.3.2](https://github.com/applitools/eyes.sdk.php/releases/tag/v1.3.2)

**Pull request closed without merging**
